jms_serializer:
    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'
        json_serialization:
            options:
                - JSON_UNESCAPED_SLASHES
                - JSON_PRESERVE_ZERO_FRACTION
    metadata:
        directories:
            KnpPaginatorBundle:
                namespace_prefix: "Knp\\Bundle\\PaginatorBundle"
                path: "%kernel.project_dir%/config/serializer/KnpPaginatorBundle"
            KnpPager:
                namespace_prefix: "Knp\\Component\\Pager"
                path: "%kernel.project_dir%/config/serializer/KnpPager"
    property_naming:
        id: 'jms_serializer.identical_property_naming_strategy'
        separator: ''
        lower_case: false
