Knp\Bundle\PaginatorBundle\Pagination\SlidingPagination:
    exclusion_policy: ALL
    properties:
        route:
            expose: true
            groups: ["sliding_paginator"]
        params:
            expose: true
            groups: ["sliding_paginator"]
        pageRange:
            expose: true
            groups: ["sliding_paginator"]
        template:
            expose: true
            groups: ["sliding_paginator"]
        sortableTemplate:
            expose: true
            groups: ["sliding_paginator"]
        filtrationTemplate:
            expose: true
            groups: ["sliding_paginator"]
